//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLUpgrade.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLUpgrade.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \DiagramsAttributePresentation.xml.
        /// </summary>
        internal static string AttributeFileName {
            get {
                return ResourceManager.GetString("AttributeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Diagrams defaults path.
        /// </summary>
        internal static string DefaultPathPrompt {
            get {
                return ResourceManager.GetString("DefaultPathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Diagrams.
        /// </summary>
        internal static string Diagrams {
            get {
                return ResourceManager.GetString("Diagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrams Upgrade.
        /// </summary>
        internal static string DiagramsUpgrade {
            get {
                return ResourceManager.GetString("DiagramsUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFoundCaption {
            get {
                return ResourceManager.GetString("FileNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Presentation xml file could not be found in the selected path. Please select the appropriate folder..
        /// </summary>
        internal static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not selected.
        /// </summary>
        internal static string FolderNotSelectedCaption {
            get {
                return ResourceManager.GetString("FolderNotSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute presentation file not found.
        /// </summary>
        internal static string IncorrectFolderCaption {
            get {
                return ResourceManager.GetString("IncorrectFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute presentation file not found. Please Select the correct folder.
        /// </summary>
        internal static string IncorrectFolderMessage {
            get {
                return ResourceManager.GetString("IncorrectFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder selected. Plese select Diagrams default forlder.
        /// </summary>
        internal static string NoSelectionMessage {
            get {
                return ResourceManager.GetString("NoSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upgraded Successfully.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
    }
}
